## Namespace of the robot
namespace: "ego"

## Number of qbAdvance Motors
joints_number: 10

## Joints name
joints_name: 
 - "base_to_left_shoulder"
 - "shoulder_to_left_arm"
 - "arm_to_left_elbow"
 - "elbow_to_left_forearm"
 - "forearm_to_left_EE"
 - "base_to_right_shoulder"
 - "shoulder_to_right_arm"
 - "arm_to_right_elbow"
 - "elbow_to_right_forearm"
 - "forearm_to_right_EE"
 
## Preset
initial_preset: [0.4, 0.3, 0.3, 0.3, 0.3, 0.4, 0.3, 0.3, 0.3, 0.3]

## topic name of des equilibrium positions
sub_topic_name: '/frank_q_des'
