float64 right_meas_neck_shaft
float64 left_meas_neck_shaft  

float64[] right_meas_arm_shaft
float64[] right_meas_arm_m1
float64[] right_meas_arm_m2
float64[] right_q_eq
float64[] right_q_preset
float64[] right_q_tau_link_elastic
float64[] right_stiff_link
float64[] right_gamma

float64[] left_meas_arm_m1
float64[] left_meas_arm_m2
float64[] left_meas_arm_shaft
float64[] left_q_eq
float64[] left_q_preset
float64[] left_q_tau_link_elastic
float64[] left_stiff_link
float64[] left_gamma


float64 right_weight
float64 left_weight