right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_link_to_right_shoulder_flange
    - right_shoulder_cube_to_right_arm_flange
    - right_arm_cube_to_right_elbow_flange_sensor
    - right_elbow_cube_to_right_forearm_flange
    - right_forearm_cube_to_right_wrist_flange
    - right_wrist_to_right_hand
  gains:
    base_link_to_right_shoulder_flange:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_cube_to_right_arm_flange:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_cube_to_right_elbow_flange_sensor:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_elbow_cube_to_right_forearm_flange:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_forearm_cube_to_right_wrist_flange:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_wrist_to_right_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1